apiVersion: apps/v1
kind: Deployment
metadata:
  name: custard-frontend-admin-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      ver: custard-frontend-admin-v1
  template:
    metadata:
      name: pod4
      labels:
        ver: custard-frontend-admin-v1
    spec:
      containers:
        - name: container
          image: hyeon28/custard_admin_frontend:test
      terminationGracePeriodSeconds: 0



